---
# elementos das paginas

## home
btn_restaurante: 'div[class*=jumbotron] a[href="/restaurants"]'

## lista restaurantes
menu_restaurants: '.restaurant-item' 

# restaurante

menu_produtos: '.menu-item-info-box'
detail_rest: '#detail'
cart: '.add-to-cart'

#cart view

box_cart: '#cart'
total_cart: 'tr'
total_cart_text: 'td'
iten_rmv_cart: 'table tbody tr'
rmv_cart: '.danger'

